export { VueJsIcon } from "./vueIcon";
export { MiroIcon } from "./miroIcon";
export { CssIcon } from "./cssIcon";
export { ReactIcon } from "./reactIcon";
export { NodeJsIcon } from "./nodeIcon";
export { HtmlIcon } from "./htmlIcon";
export { JSIcon } from "./jsIcon";

export { MakalaBoxIcon } from "./makalaBoxIcon";
export { DirectoryIcon } from "./directoryIcon";
export { HomeIcon } from "./homeIcon";
export { PictureIcon } from "./pictureIcon";
export { PlumpIcon } from "./plumpIcon";
export { PhythonIcon } from "./pythonIcon";
export { PlanetIcon } from "./planetIcon";
export { WhatsappIcon } from "./whatsappIcon"
export { GmailIcon } from "./GmailIcon"
export { InstagramIcon } from './InstagramIcon'
export { ArrowIcon } from './ArrowIcon'
