export { Applicant } from "./applicant";
export { Tab } from "./tab";
export { Review, ReviewsDetails } from "./reviews";
export { HomeHero } from "./hero";
export { ContactSection } from "./ContactSection";
export { AboutAccordion } from "./AboutAccordion";
export { Hero } from "./aboutHero";
export { ProjectsGrid } from "./projectCards";
export { SpecialHero } from "./specialHero";
export { TrainingProgram } from "./trainingProgram";
export { Footer } from "./footer";
export { Startup } from "./startup";
export { AskedQuestions } from "./askedQuestions";
export { Speciality } from "./speciality";
export { Header } from "./header";
export { ParlamentList } from "./parlamentList";
